// UI components set (buttons) JSON definitions
// Each component: { id, slug, name, description, json }

export const uiComponents = [
  {
    id: 1,
    slug: "button-primary",
    name: "Primary Button",
    description: "Solid brand-colored button with rounded corners.",
    json: {
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 200,
          height: 56,
          name: "Button",
          fill: "#4f46e5",
          stroke: "#4f46e5",
          borderWidth: 1,
          borderRadius: 28,
          opacity: 1,
          locked: true,
        },
        {
          id: 2,
          type: "text",
          x: 50,
          y: 18,
          width: 120,
          height: 24,
          text: "Click Me",
          fontSize: 18,
          textColor: "#ffffff",
          opacity: 1,
          locked: true,
        },
      ],
      comments: [],
    },
  },
  {
    id: 2,
    slug: "button-secondary",
    name: "Secondary Button",
    description: "Neutral button with subtle border.",
    json: {
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 200,
          height: 56,
          name: "Button",
          fill: "#ffffff",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 28,
          opacity: 1,
          locked: true,
        },
        {
          id: 2,
          type: "text",
          x: 56,
          y: 18,
          width: 120,
          height: 24,
          text: "Learn More",
          fontSize: 18,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
      ],
      comments: [],
    },
  },
  {
    id: 3,
    slug: "button-outline",
    name: "Outline Button",
    description: "Transparent button with strong outline.",
    json: {
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 220,
          height: 56,
          name: "Button",
          fill: "#ffffff",
          stroke: "#4f46e5",
          borderWidth: 2,
          borderRadius: 28,
          opacity: 1,
          locked: true,
        },
        {
          id: 2,
          type: "text",
          x: 40,
          y: 18,
          width: 140,
          height: 24,
          text: "Get Started",
          fontSize: 18,
          textColor: "#4f46e5",
          opacity: 1,
          locked: true,
        },
      ],
      comments: [],
    },
  },
  {
    id: 4,
    slug: "button-pill",
    name: "Pill Button",
    description: "Full-pill style for prominent actions.",
    json: {
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 240,
          height: 60,
          name: "Button",
          fill: "#111827",
          stroke: "#111827",
          borderWidth: 1,
          borderRadius: 999,
          opacity: 1,
          locked: true,
        },
        {
          id: 2,
          type: "text",
          x: 80,
          y: 20,
          width: 120,
          height: 24,
          text: "Continue",
          fontSize: 18,
          textColor: "#ffffff",
          opacity: 1,
          locked: true,
        },
      ],
      comments: [],
    },
  },
  {
    id: 5,
    slug: "button-gradient",
    name: "Gradient Button",
    description: "Eye-catching gradient style.",
    json: {
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 240,
          height: 60,
          name: "Button",
          fill: "linear-gradient(#06b6d4,#3b82f6)",
          stroke: "#3b82f6",
          borderWidth: 1,
          borderRadius: 30,
          opacity: 1,
          locked: true,
        },
        {
          id: 2,
          type: "text",
          x: 80,
          y: 20,
          width: 120,
          height: 24,
          text: "Sign Up",
          fontSize: 18,
          textColor: "#ffffff",
          opacity: 1,
          locked: true,
        },
      ],
      comments: [],
    },
  },
];

export const getComponentBySlug = (slug) =>
  uiComponents.find((c) => c.slug === slug);
