// Email templates JSON definitions
// Each template: { id, slug, name, description, json }

export const emailTemplates = [
  {
    id: 1,
    slug: "welcome-email",
    name: "Welcome Email",
    description: "Friendly welcome with hero text and CTA.",
    json: {
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 800,
          height: 1200,
          name: "Email BG",
          fill: "#ffffff",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 0,
          opacity: 1,
          locked: true,
        },
        {
          id: 2,
          type: "text",
          x: 60,
          y: 80,
          width: 680,
          height: 40,
          text: "Welcome to Our Product",
          fontSize: 28,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 3,
          type: "text",
          x: 60,
          y: 140,
          width: 680,
          height: 60,
          text: "We're excited to have you on board.",
          fontSize: 18,
          textColor: "#374151",
          opacity: 1,
          locked: true,
        },
        {
          id: 4,
          type: "rectangle",
          x: 60,
          y: 220,
          width: 200,
          height: 50,
          name: "CTA",
          fill: "#4f46e5",
          stroke: "#4f46e5",
          borderWidth: 1,
          borderRadius: 25,
          opacity: 1,
          locked: true,
        },
        {
          id: 5,
          type: "text",
          x: 102,
          y: 235,
          width: 140,
          height: 24,
          text: "Get Started",
          fontSize: 16,
          textColor: "#ffffff",
          opacity: 1,
          locked: true,
        },
      ],
      comments: [],
    },
  },
  {
    id: 2,
    slug: "reset-password",
    name: "Reset Password",
    description: "Instructions with reset button.",
    json: {
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 800,
          height: 1200,
          name: "Email BG",
          fill: "#ffffff",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 0,
          opacity: 1,
          locked: true,
        },
        {
          id: 2,
          type: "text",
          x: 60,
          y: 80,
          width: 680,
          height: 40,
          text: "Reset your password",
          fontSize: 26,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 3,
          type: "text",
          x: 60,
          y: 140,
          width: 680,
          height: 60,
          text: "Click the button below to set a new password.",
          fontSize: 18,
          textColor: "#374151",
          opacity: 1,
          locked: true,
        },
        {
          id: 4,
          type: "rectangle",
          x: 60,
          y: 220,
          width: 240,
          height: 50,
          name: "CTA",
          fill: "#ef4444",
          stroke: "#ef4444",
          borderWidth: 1,
          borderRadius: 25,
          opacity: 1,
          locked: true,
        },
        {
          id: 5,
          type: "text",
          x: 110,
          y: 235,
          width: 140,
          height: 24,
          text: "Reset Password",
          fontSize: 16,
          textColor: "#ffffff",
          opacity: 1,
          locked: true,
        },
      ],
      comments: [],
    },
  },
];

export const getEmailTemplateBySlug = (slug) =>
  emailTemplates.find((t) => t.slug === slug);
