// Website templates with JSON configurations
// Each template: { id, slug, name, description, json }

export const templates = [
  {
    id: 1,
    slug: "saas-landing",
    name: "SaaS Landing",
    description:
      "Modern SaaS landing page with hero, features and a clear CTA.",
    json: {
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          name: "Page Background",
          fill: "#f8fafc",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 0,
          opacity: 1,
          locked: true,
        },
        {
          id: 2,
          type: "rectangle",
          x: 40,
          y: 30,
          width: 1840,
          height: 80,
          name: "Navbar",
          fill: "#ffffff",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 40,
          opacity: 1,
          locked: true,
        },
        {
          id: 3,
          type: "text",
          x: 80,
          y: 55,
          width: 200,
          height: 30,
          text: "ELM",
          fontSize: 26,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 4,
          type: "text",
          x: 900,
          y: 58,
          width: 80,
          height: 24,
          text: "Features",
          fontSize: 18,
          textColor: "#374151",
          opacity: 1,
          locked: true,
        },
        {
          id: 5,
          type: "text",
          x: 1020,
          y: 58,
          width: 80,
          height: 24,
          text: "Pricing",
          fontSize: 18,
          textColor: "#374151",
          opacity: 1,
          locked: true,
        },
        {
          id: 6,
          type: "text",
          x: 1130,
          y: 58,
          width: 80,
          height: 24,
          text: "Contact",
          fontSize: 18,
          textColor: "#374151",
          opacity: 1,
          locked: true,
        },
        {
          id: 7,
          type: "rectangle",
          x: 1600,
          y: 45,
          width: 220,
          height: 50,
          name: "CTA Button",
          fill: "#4f46e5",
          stroke: "#4f46e5",
          borderWidth: 1,
          borderRadius: 25,
          opacity: 1,
          locked: true,
        },
        {
          id: 8,
          type: "text",
          x: 1655,
          y: 60,
          width: 120,
          height: 24,
          text: "Get Started",
          fontSize: 18,
          textColor: "#ffffff",
          opacity: 1,
          locked: true,
        },
        {
          id: 9,
          type: "rectangle",
          x: 120,
          y: 160,
          width: 1680,
          height: 360,
          name: "Hero Section",
          fill: "#ffffff",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 24,
          opacity: 1,
          locked: true,
        },
        {
          id: 10,
          type: "text",
          x: 200,
          y: 230,
          width: 800,
          height: 60,
          text: "Build stunning products faster than ever",
          fontSize: 42,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 11,
          type: "text",
          x: 200,
          y: 300,
          width: 700,
          height: 60,
          text: "Design, prototype, and launch modern applications with a powerful visual editor.",
          fontSize: 20,
          textColor: "#4b5563",
          opacity: 1,
          locked: true,
        },
        {
          id: 12,
          type: "rectangle",
          x: 200,
          y: 380,
          width: 220,
          height: 56,
          name: "Primary CTA",
          fill: "#4f46e5",
          stroke: "#4f46e5",
          borderWidth: 1,
          borderRadius: 28,
          opacity: 1,
          locked: true,
        },
        {
          id: 13,
          type: "text",
          x: 250,
          y: 395,
          width: 140,
          height: 24,
          text: "Start Free Trial",
          fontSize: 18,
          textColor: "#ffffff",
          opacity: 1,
          locked: true,
        },
        {
          id: 14,
          type: "rectangle",
          x: 120,
          y: 560,
          width: 520,
          height: 260,
          name: "Feature Card 1",
          fill: "#ffffff",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 20,
          opacity: 1,
          locked: true,
        },
        {
          id: 15,
          type: "text",
          x: 160,
          y: 600,
          width: 400,
          height: 30,
          text: "Visual Editor",
          fontSize: 24,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 16,
          type: "text",
          x: 160,
          y: 640,
          width: 420,
          height: 80,
          text: "Drag, drop, and design interfaces visually with pixel-perfect precision.",
          fontSize: 18,
          textColor: "#4b5563",
          opacity: 1,
          locked: true,
        },
        {
          id: 17,
          type: "rectangle",
          x: 700,
          y: 560,
          width: 520,
          height: 260,
          name: "Feature Card 2",
          fill: "#ffffff",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 20,
          opacity: 1,
          locked: true,
        },
        {
          id: 18,
          type: "text",
          x: 740,
          y: 600,
          width: 400,
          height: 30,
          text: "JSON Import / Export",
          fontSize: 24,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 19,
          type: "text",
          x: 740,
          y: 640,
          width: 420,
          height: 80,
          text: "Seamlessly move designs between tools using structured JSON.",
          fontSize: 18,
          textColor: "#4b5563",
          opacity: 1,
          locked: true,
        },
        {
          id: 20,
          type: "rectangle",
          x: 1280,
          y: 560,
          width: 520,
          height: 260,
          name: "Feature Card 3",
          fill: "#ffffff",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 20,
          opacity: 1,
          locked: true,
        },
        {
          id: 21,
          type: "text",
          x: 1320,
          y: 600,
          width: 400,
          height: 30,
          text: "Production Ready",
          fontSize: 24,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 22,
          type: "text",
          x: 1320,
          y: 640,
          width: 420,
          height: 80,
          text: "Build professional UIs that scale from prototype to production.",
          fontSize: 18,
          textColor: "#4b5563",
          opacity: 1,
          locked: true,
        },
      ],
      comments: [],
    },
  },
  {
    id: 2,
    slug: "portfolio-showcase",
    name: "Portfolio Showcase",
    description:
      "Clean portfolio layout highlighting projects and a contact CTA.",
    json: {
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          name: "Background",
          fill: "#f9fafb",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 0,
          opacity: 1,
          locked: true,
        },
        {
          id: 2,
          type: "rectangle",
          x: 60,
          y: 40,
          width: 1800,
          height: 90,
          name: "Navbar",
          fill: "#ffffff",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 40,
          opacity: 1,
          locked: true,
        },
        {
          id: 3,
          type: "text",
          x: 100,
          y: 70,
          width: 220,
          height: 32,
          text: "Designer Name",
          fontSize: 24,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 4,
          type: "rectangle",
          x: 120,
          y: 180,
          width: 520,
          height: 320,
          name: "Project 1",
          fill: "#ffffff",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 24,
          opacity: 1,
          locked: true,
        },
        {
          id: 5,
          type: "text",
          x: 140,
          y: 500,
          width: 450,
          height: 24,
          text: "E-commerce redesign",
          fontSize: 18,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 6,
          type: "rectangle",
          x: 700,
          y: 180,
          width: 520,
          height: 320,
          name: "Project 2",
          fill: "#ffffff",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 24,
          opacity: 1,
          locked: true,
        },
        {
          id: 7,
          type: "text",
          x: 720,
          y: 500,
          width: 450,
          height: 24,
          text: "SaaS UI kit",
          fontSize: 18,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 8,
          type: "rectangle",
          x: 1280,
          y: 180,
          width: 520,
          height: 320,
          name: "Project 3",
          fill: "#ffffff",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 24,
          opacity: 1,
          locked: true,
        },
        {
          id: 9,
          type: "text",
          x: 1300,
          y: 500,
          width: 450,
          height: 24,
          text: "Marketing site",
          fontSize: 18,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 10,
          type: "rectangle",
          x: 1600,
          y: 60,
          width: 220,
          height: 56,
          name: "Contact CTA",
          fill: "#111827",
          stroke: "#111827",
          borderWidth: 1,
          borderRadius: 28,
          opacity: 1,
          locked: true,
        },
        {
          id: 11,
          type: "text",
          x: 1650,
          y: 78,
          width: 120,
          height: 24,
          text: "Contact",
          fontSize: 18,
          textColor: "#ffffff",
          opacity: 1,
          locked: true,
        },
      ],
      comments: [],
    },
  },
  {
    id: 3,
    slug: "ecommerce-hero",
    name: "E-commerce Hero",
    description: "Product-focused hero with CTA and three feature cards.",
    json: {
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          name: "Background",
          fill: "#ffffff",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 0,
          opacity: 1,
          locked: true,
        },
        {
          id: 2,
          type: "rectangle",
          x: 120,
          y: 160,
          width: 900,
          height: 500,
          name: "Product",
          fill: "#f1f5f9",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 24,
          opacity: 1,
          locked: true,
        },
        {
          id: 3,
          type: "text",
          x: 1100,
          y: 220,
          width: 700,
          height: 60,
          text: "Meet your new favorite gadget",
          fontSize: 38,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 4,
          type: "text",
          x: 1100,
          y: 290,
          width: 650,
          height: 60,
          text: "High performance, sleek design, and a price you'll love.",
          fontSize: 20,
          textColor: "#4b5563",
          opacity: 1,
          locked: true,
        },
        {
          id: 5,
          type: "rectangle",
          x: 1100,
          y: 360,
          width: 220,
          height: 56,
          name: "Buy CTA",
          fill: "#ef4444",
          stroke: "#ef4444",
          borderWidth: 1,
          borderRadius: 28,
          opacity: 1,
          locked: true,
        },
        {
          id: 6,
          type: "text",
          x: 1158,
          y: 378,
          width: 120,
          height: 24,
          text: "Buy Now",
          fontSize: 18,
          textColor: "#ffffff",
          opacity: 1,
          locked: true,
        },
        {
          id: 7,
          type: "rectangle",
          x: 120,
          y: 720,
          width: 520,
          height: 260,
          name: "Feature 1",
          fill: "#ffffff",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 20,
          opacity: 1,
          locked: true,
        },
        {
          id: 8,
          type: "text",
          x: 160,
          y: 760,
          width: 420,
          height: 30,
          text: "Fast shipping",
          fontSize: 22,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 9,
          type: "text",
          x: 160,
          y: 800,
          width: 420,
          height: 80,
          text: "Get your order delivered in 2 days.",
          fontSize: 16,
          textColor: "#4b5563",
          opacity: 1,
          locked: true,
        },
      ],
      comments: [],
    },
  },
  {
    id: 4,
    slug: "blog-header",
    name: "Blog Header",
    description: "Editorial style header with title, subtitle and author.",
    json: {
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          name: "Background",
          fill: "#f8fafc",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 0,
          opacity: 1,
          locked: true,
        },
        {
          id: 2,
          type: "text",
          x: 200,
          y: 220,
          width: 1200,
          height: 80,
          text: "Design systems: the secret to scaling UI",
          fontSize: 48,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 3,
          type: "text",
          x: 200,
          y: 310,
          width: 1000,
          height: 60,
          text: "A practical guide to building and maintaining design systems.",
          fontSize: 22,
          textColor: "#374151",
          opacity: 1,
          locked: true,
        },
        {
          id: 4,
          type: "text",
          x: 200,
          y: 380,
          width: 600,
          height: 24,
          text: "By Alex Designer · Jan 2026",
          fontSize: 16,
          textColor: "#6b7280",
          opacity: 1,
          locked: true,
        },
      ],
      comments: [],
    },
  },
  {
    id: 5,
    slug: "dashboard-intro",
    name: "Dashboard Intro",
    description: "Dashboard splash screen with KPI cards and quick actions.",
    json: {
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          name: "Background",
          fill: "#f9fafb",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 0,
          opacity: 1,
          locked: true,
        },
        {
          id: 2,
          type: "text",
          x: 120,
          y: 160,
          width: 600,
          height: 60,
          text: "Welcome back, Aryan",
          fontSize: 36,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 3,
          type: "rectangle",
          x: 120,
          y: 240,
          width: 420,
          height: 200,
          name: "KPI 1",
          fill: "#ffffff",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 18,
          opacity: 1,
          locked: true,
        },
        {
          id: 4,
          type: "text",
          x: 160,
          y: 280,
          width: 320,
          height: 30,
          text: "Monthly revenue",
          fontSize: 18,
          textColor: "#374151",
          opacity: 1,
          locked: true,
        },
        {
          id: 5,
          type: "text",
          x: 160,
          y: 320,
          width: 320,
          height: 50,
          text: "$24,120",
          fontSize: 28,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 6,
          type: "rectangle",
          x: 560,
          y: 240,
          width: 420,
          height: 200,
          name: "KPI 2",
          fill: "#ffffff",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 18,
          opacity: 1,
          locked: true,
        },
      ],
      comments: [],
    },
  },
  {
    id: 6,
    slug: "event-landing",
    name: "Event Landing",
    description: "Event hero with title, date, location and registration CTA.",
    json: {
      elements: [
        {
          id: 1,
          type: "rectangle",
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          name: "Background",
          fill: "#f1f5f9",
          stroke: "#e5e7eb",
          borderWidth: 1,
          borderRadius: 0,
          opacity: 1,
          locked: true,
        },
        {
          id: 2,
          type: "text",
          x: 120,
          y: 200,
          width: 1200,
          height: 80,
          text: "Design Conf 2026",
          fontSize: 56,
          textColor: "#111827",
          opacity: 1,
          locked: true,
        },
        {
          id: 3,
          type: "text",
          x: 120,
          y: 280,
          width: 800,
          height: 60,
          text: "March 21-23 · Bangalore",
          fontSize: 24,
          textColor: "#374151",
          opacity: 1,
          locked: true,
        },
        {
          id: 4,
          type: "rectangle",
          x: 120,
          y: 360,
          width: 240,
          height: 56,
          name: "Register CTA",
          fill: "#4f46e5",
          stroke: "#4f46e5",
          borderWidth: 1,
          borderRadius: 28,
          opacity: 1,
          locked: true,
        },
        {
          id: 5,
          type: "text",
          x: 176,
          y: 378,
          width: 160,
          height: 24,
          text: "Register Now",
          fontSize: 18,
          textColor: "#ffffff",
          opacity: 1,
          locked: true,
        },
      ],
      comments: [],
    },
  },
];

export const getTemplateBySlug = (slug) =>
  templates.find((t) => t.slug === slug);
